name: 🚀 Deploy to Strato via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 📤 Deploy with SFTP
        uses: pressidium/lftp-deploy@v1
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          protocol: sftp
          local-dir: ./ # alles aus deinem Repository-Root
          server-dir: /portfolio/
